# Generated by Django 5.1.1 on 2024-09-17 10:33

import datetype
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateField(default=datetype.DateTime.time)),
                ('type', models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('KL', 'Kiwi'), ('PL', 'Plain'), ('EL', 'Elaichi')], default='ML', max_length=2)),
            ],
        ),
    ]
