# Generated by Django 5.1.1 on 2024-09-17 11:09

import datetype
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='date_added',
            field=models.DateField(default=datetype.DateTime.now),
        ),
    ]
